services:
  manga-delivery:
    image: ghcr.io/leogsantos/manga-delivery:latest
    env_file:
      - .env
    environment:
      - PYTHONUNBUFFERED=1
    volumes:
      - ./secrets:/app/secrets
      - ./output:/app/output
      - ./downloads:/app/downloads
    restart: "no"
